name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install pnpm
      - uses: pnpm/action-setup@v4

      # Setup Node.js and cache pnpm store
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Install deps (no tests)
      - run: pnpm install --frozen-lockfile

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
  
      # Setup pnpm
      - uses: pnpm/action-setup@v4
  
      # Setup Node.js + GitHub Packages registry
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
  
      # Install deps
      - run: pnpm install --frozen-lockfile
  
      # Publish, skipping the git-branch check
      - run: |
          pnpm publish \
            --access public \
            --registry https://npm.pkg.github.com/ \
            --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
