name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install pnpm
      - uses: pnpm/action-setup@v4

      # Setup Node.js + cache pnpm store
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Install deps only
      - run: pnpm install --frozen-lockfile

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      # Re-setup pnpm
      - uses: pnpm/action-setup@v4

      # Setup Node.js + GitHub Packages registry
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      # Install deps & publish (skip git-branch check)
      - run: pnpm install --frozen-lockfile
      - run: |
          pnpm publish \
            --access public \
            --registry https://npm.pkg.github.com/ \
            --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
